<?php
require_once __DIR__ . "/phpmailer/src/Exception.php";
require_once __DIR__ . "/phpmailer/src/PHPMailer.php";
require_once __DIR__ . "/phpmailer/src/SMTP.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require_once __DIR__ . "/turnstile.php";

header('Content-Type: text/plain; charset=utf-8');
header('Cache-Control: no-store');

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    echo 'NOK';
    return;
}

$authEmail = "web@aikidolevice.sk";
$authPass = "A!kidoLevice1Web";
$emailTo = "info@aikidolevice.sk";
$subject = "Správa z kontaktného formulára Aikido Levice";

function validateInputs() {
	return isset($_POST["from"], $_POST["message"])
	    && is_string($_POST["from"])
	    && is_string($_POST["message"])
	    && !empty($_POST["from"])
	    && filter_var($_POST["from"],FILTER_VALIDATE_EMAIL)
	    && trim($_POST["message"]) !== '';
}


/// main program
if (!validateInputs()) {
	http_response_code(400);
	echo "NOK";
	return;
}

// Generated by Vite from .env, only in the production build.
$configPath = __DIR__ . '/contact-config.php';
if (!is_file($configPath) || !function_exists('curl_init')) {
    http_response_code(503);
    echo 'NOK';
    return;
}
$config = require $configPath;
$secret = $config['turnstileSecretKey'] ?? '';
if (!is_string($secret) || $secret === '') {
    http_response_code(503);
    echo 'NOK';
    return;
}

if (!validateTurnstile($_POST['cf-turnstile-response'] ?? '', $secret)) {
    http_response_code(403);
    echo 'NOK';
    return;
}

$mail = new PHPMailer(true);
try {
    $mail->isSMTP();
    $mail->CharSet = 'UTF-8';
    $mail->Host = 'smtp.m1.websupport.sk';
    $mail->SMTPAuth = true;
    $mail->Username = $authEmail;
    $mail->Password = $authPass;
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;
    $mail->setFrom($authEmail);
    $mail->addAddress($emailTo);
    $mail->addReplyTo($_POST["from"]);
    $mail->isHTML(false);
    $mail->Subject = $subject;
    $mail->Body = "Odosielateľ: " . $_POST["from"]
        . "\n\nSpráva:\n" . $_POST["message"];
    $mail->send();

    echo 'OK';

} catch (Exception $e) {
    http_response_code(500);
    echo "NOK";
}

?>
